server:
  port: 8081

spring:
  application:
    name: service1

management:
  tracing:
    sampling:
      probability: 1.0  # Ensures all requests are traced

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans  # Correct Zipkin endpoint
